---
- hosts: localhost
  vars_files:
    - vars.yml
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Enter your local user password"
      private: yes
  roles:
    - { role: geerlingguy.homebrew }
