- hosts: localhost
  vars_files:
    - vars.yml
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Enter your local user password"
      private: yes
  roles:
    - { role: geerlingguy.homebrew }
  tasks:
    - name: Upgrade ZSH
      shell: export ZSH=$ZSH /bin/sh $ZSH/tools/upgrade.sh
    - name: Homebrew Cleanup
      shell: brew cleanup
    - name: Update OSX
      shell: softwareupdate -i -a
